num1 = int(input("enter your first number"))
num2 = int(input("enter your second number"))
num3 = int(input("enter your third number"))
num4 = int(input("enter your fourth number"))
num5 = int(input("enter your fifth number"))
print((num1 + num2) / num3 - num4*num5 % num2)